[project]
name = "callmemaybe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.14.0",
    "argparse>=1.4.0",
    "flake8>=7.3.0",
    "llm-sdk",
    "mypy>=2.3.1",
    "numpy>=2.5.3",
    "pydantic>=2.13.5",
    "pylance>=11.0.0",
    "python-statemachine>=3.2.1",
    "regex>=2026.9.3",
    "tokenizer>=3.6.4",
    "torch>=2.14.0",
]

[tool.uv.workspace]
members = [
    "llm_sdk",
]

[tool.uv.sources]
llm-sdk = { workspace = true }
